./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
./zzz<1.c|./zzz|./zzz>zzzout &
